### PR TITLE
fix: return fake version for `performance.timeOrigin`

### LINKED ISSUE #514: Support `performance.timeOrigin` property
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

-   FakeTimers version : 13.0.5
-   Environment : MacOS
-   Other libraries you are using: jest, @sentry/react

**What did you expect to happen?**

I expected that `performance.timeOrigin` (https://developer.mozilla.org/en-US/docs/Web/API/Performance/timeOrigin) would return a valid value with fake timers enabled in jest.

**What actually happens**

`performance.timeOrigin` is set to NOOP [here](https://github.com/sinonjs/fake-timers/blob/7861c930e8f9aaa9d227431623cc82347aff0291/src/fake-timers-src.js#L1843).

**How to reproduce**

```bash
git clone https://github.com/rriski/fake-timers-timeOrigin-repro.git
npm run test
# --> test fails
# Uncomment `doNotFake` in jest.config.js
npm run test
# --> test passes
```

**Additional information**

* Related to #493
* `@sentry/react` uses the performance API to set the session starting time, see [session.ts](https://github.com/getsentry/sentry-javascript/blob/6331d7ced7373e3f351ffacb71af54392c19acda/packages/core/src/session.ts#L14)

### PR DESCRIPTION
**Pull request by rriski**
Fixes #514

#### Purpose (TL;DR) - mandatory

Return valid value for `performance.timeOrigin` instead of `NOOP`. This fixes an issue in tests that depend on `performance.timeOrigin` having a valid value.

#### Background (Problem in detail)  - optional

See #514

#### Solution  - optional

Set `performance.timeOrigin` to a dummy value. I'm not sure if 0 is better than setting the value to `clock.now`. When testing `performance.timeOrigin` in Chrome Console I can see that the value is set to the timestamp when the window was opened:

```
> globalThis.performance.timeOrigin
1733227796841
```

There is further information in MDS docs on how the value is supposed to be set: https://developer.mozilla.org/en-US/docs/Web/API/Performance/timeOrigin#value

### CODE REVIEW

File: src/fake-timers-src.js [hunk 1]
```diff
@@ -1848,6 +1848,8 @@ function withGlobal(_global) {
                     new FakePerformanceEntry(name, "mark", 0, 0);
                 clock.performance.measure = (name) =>
                     new FakePerformanceEntry(name, "measure", 0, 100);
+                // ensure `timeOrigin` returns a valid value
+                clock.performance.timeOrigin = 0;
```
Comment (fatso83) [inline src/fake-timers-src.js:1852]: > If the current [Document](https://developer.mozilla.org/en-US/docs/Web/API/Document) is the first one loaded in the Window, the time origin is the time at which the browser context was created.

Best fit is likely the installed time

Comment (rriski) [reply src/fake-timers-src.js:1852]: Would this work?

```js
clock.performance.timeOrigin = config.now ? getEpoch(config.now) : new Date().getTime();
```

Comment (fatso83) [reply src/fake-timers-src.js]: A bit redundant, given that `getEpoch` already does just that. I trimmed it away and also made the test a bit tighter/more specific.

Comment (rriski) [reply src/fake-timers-src.js]: Thank you!
